language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew uninstall xctool
    - brew install xctool --HEAD
    - pod install
script: xctool -workspace NSString+Ruby.xcworkspace -scheme "NSStringRubyTests" test -sdk iphonesimulator -arch i386
